// <auto-generated />
using System;
using HyperDevCase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HyperDevCase.Migrations
{
    [DbContext(typeof(CaseContext))]
    [Migration("20220711163115_initial1")]
    partial class initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HyperDevCase.Models.Company", b =>
                {
                    b.Property<short>("Companyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Companyid"), 1L, 1);

                    b.Property<string>("CompanyAdress")
                        .IsRequired()
                        .HasColumnType("nchar(100)");

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("CompanyDistrict")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nchar(100)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxAdministration")
                        .IsRequired()
                        .HasColumnType("nchar(100)");

                    b.Property<long>("TaxNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Companyid");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HyperDevCase.Models.Department", b =>
                {
                    b.Property<short>("Departmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Departmentid"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Companyid")
                        .HasColumnType("smallint");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("DepartmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Departmentid");

                    b.HasIndex("Companyid");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HyperDevCase.Models.Department", b =>
                {
                    b.HasOne("HyperDevCase.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("Companyid");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
